service: step-functions-example

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
  ciao:
    handler: handler.ciao

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: "hello"
      definition:
        Comment: "A Hello World example"
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
            Next: CiaoWorld
          CiaoWorld:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-ciao"
            End: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
